name: GensouAddons
version: '${version}'
main: net.gensokyoreimagined.gensouaddons.GensouAddons
api-version: 1.20
depend: [Oraxen]
commands:
  testcommand:
    description: desc
    usage: /<command>

